---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base
  amd64: ghcr.io/hassio-addons/debian-base
  armhf: ghcr.io/hassio-addons/debian-base
  armv7: ghcr.io/hassio-addons/debian-base
  i386: ghcr.io/hassio-addons/debian-base
