---
build_from:
  aarch64: arm64v8/debian
  amd64: ghcr.io/hassio-addons/debian-base
  armhf: ghcr.io/hassio-addons/debian-base
  armv7: ghcr.io/hassio-addons/debian-base
  i386: ghcr.io/hassio-addons/debian-base
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev